### ISSUE TITLE
sidebars in mobile view

### ISSUE THREAD

**Issue by Fotofantasten** [govfresh/govpress#96]
Hello Govpress staff.
 
I have to tell you this first… I absolutely love the clean, simple but effective style you have brought to this theme and it works so damn well!
 
I just have one tiny request. I’ve tried to google my answer, but can’t find a solution.
 
When visiting the homepage from a mobile phone or from a tablet, the sidebar is pushed down below the page content.

The problem I have with my site, is that I use the sidebar for a sub-menu system plugin and I want the menu to be shown above the content (or maybe at both places).
 
Is it possible to do this, and if it is, can you show me how to move the code in a correct way in the php files? 
 
 
Best Regards
Richard Nilsson

**Comment by devinsays** [comment]
Hi. You would need to customize the theme in order to move the sidebar location in the markup. Every template (such as index.php) that makes a ```<?php get_sidebar(); ?>``` call would need to have that moved up above the main content area. You'd also likely need to update some of the styling to ensure the floating of those areas on the desktop layout still works.

However, we can't offer personalized support for customization requests. If you need help, we recommend hiring a developer or asking in the WordPress support forums: https://wordpress.org/support/forum/themes-and-templates

**Comment by lukefretwell** [comment]
Thank you @devinsays!
